[package]
name = "perf_event_open"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2"
byteorder = "1"
parking_lot = "0.11"
log = "0.4"
